### ISSUE TITLE
generate wrapper should work as indicated in README.md

### ISSUE THREAD

**Issue by bajacondor** [TriggerMail/rules_pyz#1]
Thanks for this work.  

The instructions in the README.md do not work correctly for a first time run.  

Instruction #3 asks you to place `load("//third_party/pypi:pypi_rules.bzl", "pypi_repositories")
pypi_repositories()` in your WORKSPACE.
Instruction #4 asks you to run `bazel build @com_bluecore_rules_pyz//pypi:pip_generate_wrapper`

This will error out since 
```
bazel build @com_bluecore_rules_pyz//pypi:pip_generate_wrapper
bazel-bin/external/com_bluecore_rules_pyz/pypi/pip_generate_wrapper \
    -requirements requirements.txt \
    -output third_party/pypi/pypi_rules.bzl \
    -wheelURLPrefix http://example.com/
``` 
is what _creates_ the pypi_rules.bzl in the first place.
This seems to be a "chicken and egg" situation.  How do you handle this in a CI environment?

Thank you,
David

**Comment by evanj** [comment]
Sorry I didn't notice this, my Github notifications are all screwed up. Oops great point sorry. The order of operations is incorrect. I just attempted to fix the README.

This will be fine in CI since you generate a "snapshot" of all the requirements you want in development. In CI, it just "rebuilds" exactly the configuration you used in development. This is the same way `yarn.lock` works with Yarn, or bazel-deps works for Maven: https://github.com/johnynek/bazel-deps
