### ISSUE TITLE
multiple requirements.txt files

### ISSUE THREAD

**Issue by therc** [TriggerMail/rules_pyz#41]
How does one set up a monorepo with multiple packages, each using their own requirements.txt?

Using one //third_party/pypi would be the best, but perhaps right now the easiest is to use //third_party/LOCALPACKAGE/pypi/... or //third_party/pypi/LOCALPACKAGE/...

**Comment by evanj** [comment]
The `pip_generate` tool currently does not generate version-specific dependencies, partially since it relies on pip to resolve dependencies, and it can't have more than one installed. This means you have two choices:

* Create a "merged" requirements.txt and feed that to `pip_generate`, to create a single `pypi_rules.bzl` file with all the merged dependencies (this is what I do)
* Generate separate `pypi_rules.bzl` files for each separate package, and have their `BUILD` files reference the correct ones.

I think it depends on if you want to use a single, consistent version of every Python package across your code, or if you want the separate packages to be able to specify conflicting versions. IMO,  I think an advantage of a monorepo is you can upgrade everything at once, so I would go with the single "merged" requirements.txt.

Hope that helps!
